CREATE TABLE IF NOT EXISTS Customers(
CustomerId INT PRIMARY KEY,
CustomerName VARCHAR(50) NOT NULL,
ContactName VARCHAR(50),
Address VARCHAR(50) NOT NULL,
City VARCHAR(50)NOT NULL,
PostalCode VARCHAR(30) NOT NULL,
Country VARCHAR(50) NOT NULL
)




