CREATE TABLE IF NOT EXISTS Employees (
    EmployeeID INT PRIMARY KEY,
    LastName VARCHAR(50) NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    BirthDate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    Photos VARCHAR(50) NOT NULL,
    Notes VARCHAR(800)
);

