CREATE TABLE IF NOT EXISTS Orders (
    OrderID INT PRIMARY KEY,
    CustomerID INT NOT NULL,
    EmployeeID INT NOT NULL,
    OrderDate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ShipperID INT NOT NULL,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID),
    FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEES(EmployeeID),
    FOREIGN KEY (ShipperID) REFERENCES SHIPPERS(ShipperID)
);



